databases:
  - name: pulsevet-db
    plan: free

services:
  - type: web
    name: pulsevet-backend-oregon
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsevet-db
          property: connectionString
      - key: NODE_ENV
        value: production
