# A estrutura correta, separando databases e services.

databases:
  - name: pulsevet-db      # Define o banco de dados aqui
    plan: free
    # Não precisa de tipo, a seção 'databases' já diz o que é.

services:
  - type: web             # Define o serviço web aqui
    name: pulsevet-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:         # A FORMA CORRETA DE CONECTAR
          name: pulsevet-db
          property: connectionString
