# Certidão de Nascimento do VetSystem na Render

services:
  # --- O Banco de Dados ---
  - type: pserv # Private Service (Banco de Dados)
    name: pulsevet-db # O nome EXATO do seu banco de dados na Render
    plan: free # Plano gratuito
    # A Render vai usar a imagem padrão do PostgreSQL para esta versão
    # Não precisamos de build ou start command para o banco

  # --- O Backend (Nosso Aplicativo) ---
  - type: web
    name: pulsevet-backend # O nome EXATO do seu backend na Render
    plan: free # Plano gratuito
    env: node
    # Aponta para a pasta correta dentro do repositório
    rootDir: backend
    # Comandos de Build e Start
    buildCommand: "npm install && npm run build" # npm run build já contém o prisma generate
    startCommand: "npm start"
    # A MÁGICA ACONTECE AQUI!
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv # O tipo do serviço de onde vem a variável
          name: pulsevet-db # O nome do serviço de onde vem a variável
          property: connectionString # A propriedade que queremos pegar (a URL de conexão)
