databases:
  - name: pulsevet-db
    plan: free

services:
  - type: web
    name: pulsevet-backend
    plan: free
    env: node
    rootDir: backend
    # O build continua o mesmo, simples e limpo.
    buildCommand: "npm install && npm run build"
    # O start volta a ser simples, pois a lógica está no código.
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsevet-db
          property: connectionString
      # Adicionamos a variável NODE_ENV para o código saber que está em produção
      - key: NODE_ENV
        value: production
