databases:
  - name: pulsevet-db
    plan: free

services:
  - type: web
    name: pulsevet-backend
    plan: free
    env: node
    rootDir: backend
    # AQUI ESTÁ A MUDANÇA: O prisma generate vem para o build
    buildCommand: "npm install && npx prisma generate && npm run build"
    # O start volta a ser apenas para iniciar o servidor
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsevet-db
          property: connectionString
