# Certidão de Nascimento do VetSystem na Render (v3 - A Finalíssima)

services:
  # --- O Banco de Dados ---
  - type: pserv       # CORREÇÃO: O tipo volta a ser 'pserv' (Serviço Privado)
    name: pulsevet-db 
    runtime: postgres # A LINHA MÁGICA: Aqui dizemos que é um serviço do tipo PostgreSQL
    plan: free 

  # --- O Backend (Nosso Aplicativo) ---
  - type: web
    name: pulsevet-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv # CORREÇÃO: Apontando para o tipo de serviço correto
          name: pulsevet-db
          property: connectionString
