databases:
  - name: pulsevet-db
    plan: free

services:
  - type: web
    name: pulsevet-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: |
      npm run prisma:generate
      npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsevet-db
          property: connectionString
      - key: PRISMA_SKIP_POSTINSTALL_GENERATE
        value: "true"
