services:
  - type: web
    name: pulsevet-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm ci
      npm run build
    startCommand: |
      npm run prisma:generate
      npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsevet-db
          property: connectionString
      - key: PRISMA_SKIP_POSTINSTALL_GENERATE
        value: "true"

# Se ainda não existir, a Render cria este DB ao aplicar o render.yaml
# ou você aponta para um DB existente com o mesmo name.
databases:
  - name: pulsevet-db
    plan: free
