databases:
  - name: pulsevet-db
    plan: free

services:
  - type: web
    name: pulsevet-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pulsevet-db
          property: connectionString
      - key: NODE_ENV
        value: production
