# Certidão de Nascimento do VetSystem na Render (v2 - Corrigida)

services:
  # --- O Banco de Dados ---
  - type: db # CORREÇÃO: O tipo correto para um banco de dados gerenciado
    name: pulsevet-db 
    # O nome do banco de dados e do usuário que serão criados
    databaseName: pulsevet_db 
    databaseUser: pulsevet_db_user
    plan: free 

  # --- O Backend (Nosso Aplicativo) ---
  - type: web
    name: pulsevet-backend
    plan: free
    env: node
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: db # CORREÇÃO: Apontando para o tipo de serviço correto
          name: pulsevet-db
          property: connectionString
